### ISSUE TITLE
Should this project be archived or change ownership?

### ISSUE THREAD

**Issue by johnhunter** [gregives/eleventy-load#105]
I'm not sure this project is actively maintained. Personally I'm no longer using it and do not have the time to commit to maintenance. There are a few outstanding bugs that would probably involve significant rework. Additionally, [11ty v2](https://www.11ty.dev/blog/eleventy-v2/) has better support for processing asset files so there is less need for projects like this.

@gregives perhaps its time to archive?

**If anyone relies on this project, or wants to carry it forward please reach out.**

Thanks,
John.

**Comment by gregives** [comment]
Hi @johnhunter, first and foremost I want to say thank you for the time you've spent maintaining this project, I really appreciate it!

I no longer use 11ty or have any time to devote to this library, so I will archive it. If anyone wants to take ownership of the library, please do let me know.

Thanks,
Greg
