### ISSUE TITLE
11ty 1.0 breaks eleventy-load

### ISSUE THREAD

**Issue by andrewhayward** [gregives/eleventy-load#5]
[This change in 11ty](https://github.com/11ty/eleventy/commit/71f5943f1fa826a2b6d589cc1f49676d23b88afe#diff-3474a01da03b1df2f715477d31a8f3a01abcd3abe630a6b961e914999a04d8e2) changes the `this` referenced here:

https://github.com/gregives/eleventy-load/blob/8b6e1f52a216b951239f70933b832e89f85715ae/index.js#L199-L209

`this._config` is no longer available, causing an error to be thrown:

```
Cannot read property 'inputDir' of undefined
```

**Comment by Acccent** [comment]
Hi, can we expect a new release with this fix soone? I'm trying to get pnpm to install a specific commit, but can't get it to work...

**Comment by johnhunter** [comment]
Thanks @Acccent I'm going to re-open this as we haven't released the fix. @gregives any chance we could publish to npm? I don't have the authorisation for that.

**Comment by gregives** [comment]
Thanks @Acccent @johnhunter I will publish this to npm today or tomorrow.

**Comment by gregives** [comment]
Published v0.3.0 to npm with the fix for Eleventy v1.0, thanks @johnhunter for doing all the hard work!
